name: GitHub Projects Automation

on:
  pull_request:
    types: [closed]

jobs:
    move-issue-to-done:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo
            uses: actions/checkout@v3

          - name: Check if PR is merged
            if: github.event.pull_request.merged == true
            run: |
              echo "pull request merged, moving issue to done"

              curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -d '{"column_id": "98236657", "content_type": "Issue", \
                "content_id": "'${{ github.event.issue.id}}'"}'\
                https://api.github.com/projects/columns/98236657/cards
    